### ISSUE TITLE
Wechsel vom einfachen Modus in den Dokument-Modus

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#107]
Berechnungen im einfachen Modus werden auch im DOkumentmodus dargestellt.
Allerdings ist es im DOkumentmodus nicht möglich, Zellen zu löschen.
Sinnvoll wäre: Beim Wechsel Warnhinweis und "Alles löschen" vorher ausführen, falls bestätigt.

Oder Lennard? F5 reicht doch. Ich ziehe den Issue zurück, ... ja?

**Comment by behrenle** [comment]
Ich verstehe das Problem nicht. Eine Zelle kann mit `entf` gelöscht werden. Es gibt sonst auch den Button mit dem Mülleimer Symbol inder Toolbar.

**Comment by behrenle** [comment]
Ich verstehe das Problem nicht. Eine Zelle kann mit `entf` gelöscht werden. Es gibt sonst auch den Button mit dem Mülleimer Symbol inder Toolbar.
