### ISSUE TITLE
Link teilen

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#108]
Jeder Aufruf von Link teilen erzeugt eine neue URL.
Es wäre sinnvoll, dies machen zu können, aber auch, eine bereits erzeugte URL weiter zu verwenden:
Ich würde im PopUp einen entsprechenden Button ergänzen. Erzeuge neue URL, die beim ersten Mal teilen automatisch ausgeführt wird.

Grund: Über einen einmal geteilter Link lässt sich die Arbeit leichter nachverfolgen

**Comment by behrenle** [comment]
Ja, das fände ich prinzipiell auch eine gute Idee. Leider habe ich mich aus folgenden Grund dagegen entschieden. 
Wenn Lehrer L einen Link zu einem Übungszettel erzeugt und diesen dann seinen Schülern zukommen lässt, dann ein der böse Schüler B das Dokument öffnen, manipulieren und unter dem gleichen Link wieder abspeichern. 
Um einem solchen Berechtigungskonflikt aus dem Weg zu gehen, habe ich entschieden, dass Dokumente Read-Only sind und nicht modifiziert werden könnnen.

**Comment by cssbue** [comment]
Aber Lennard, hier müssen wir nochmal nachdenken: Im Unterricht will ich "vorrechnen" können. Also einmal den Link teilen, aber wenn ich dann aktualisiere und die Aktualisierung verteilen will, wäre es gut, wenn die SuS sich den neuen Content mit F5 holen könnten. Das ist doch OneWay und die Manipulationsmöglichkeit sehe ich nicht. Nur der, der den Link versendet, kann aktualisieren, die anderen können nur wiederholt lesen. Alles was es braucht, wäre ein neuer Link beim ersten mal Pushen oder wenn man das explizit will.
