### ISSUE TITLE
UNBEDINGT ... Shortcut zum Wechsel zwischen einfachem und dokumentmodus

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#109]
Sonst klicke ich mir hier nen Wolf ... CTRL-E CTRL-D ... noch frei? (nein, nicht der Sitzplatz) ;-)

**Comment by behrenle** [comment]
hmm ich lass es mir mal durch den kopf gehen bin aber noch nicht komplett überzeugt

**Comment by cssbue** [comment]
Ja, musst mir nicht jeden Wunsch erfüllen. Vielleicht ist das jetzt nur beim Testen relevant, später nicht mehr.
Aber schau bei Gelegenheit doch mal in deinen Posteingang ... ;-)
