### ISSUE TITLE
Keine case sensitivity bei Funktionsbezeichnern

### ISSUE THREAD

**Issue by ukalina** [behrenle/Math-Explorer#120]
Funktionsbezeichner sollten nicht case sensitive sein, um die Eingabe auf Smartphones zu erleichtern, bei denen standardmäßig Wortanfänge groß geschrieben werden.

**Comment by behrenle** [comment]
Probier einfach mal ob das so für dich in Ordnung ist und wenn ja kannst du das Issue hier selbstständig closen ;)

**Comment by ukalina** [comment]
Bin immer wieder erstaunt, was es so alles für Objekteigenschaften gibt. 
Diese Lösung gefällt mir auch besser als die case insensitive Lösung.
