### ISSUE TITLE
8.6 Gauß'sche Integralfunktion (Normalverteilung) \Phi(z)

### ISSUE THREAD

**Issue by ukalina** [behrenle/Math-Explorer#25]
Aufgabe:	Berechne \Phi(0,5) mit \Phi(z) = \int_{-\infty}^z \phi(t) dt und 
\phi(t) = 1/ \sqrt{2\pi} *e^{-0,5*t^2}
Eingabe:	cnormal(0,5)
Ausgabe:	RuntimeError

**Comment by behrenle** [comment]
Das ist ein Bug.
