### ISSUE TITLE
9.3 Vektorlänge

### ISSUE THREAD

**Issue by ukalina** [behrenle/Math-Explorer#27]
Aufgabe:	Berechne die Länge (den Betrag) des Vektors (1; -2; 2)
Eingabe:	abs([1; -2; 2])
Ausgabe:	RuntimeError

**Comment by behrenle** [comment]
`abs(n)` ist bisher nur definiert für `n \in \R`. Die Idee, dass `abs` auch Vektoren unterstützt finde ich gut. Ich werde `abs(n)` für `n \in \R^k, k \in \N` erweitern.
