### ISSUE TITLE
Übergabe von Eingabe und Ausgabe in Zwischenablage

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#38]
Die Eingabe oder Ausgabe lässt sich elegant fokussieren und der aktuelle Wert in die Zwischenablage übernehmen. CTRL-C.
Was nicht möglich ist, ist, in einem Schritt sowohl die Eingabe wie auch die Ausgabe zu übernehmen (enspricht der Protokoll-Funktionen des Termevaluators). Grob gesagt war dies mit ALT-P möglich, was ich hier ebenfalls verwenden würde, um in zwei Zeilen (evtl. mehrzeilig), die aktuellen Werte in die Zwischenablage zu kopieren. Sinnvoll?

**Comment by behrenle** [comment]
Wie soll das Format dann aussehen? Soll ich Clipboard dann `<Eingabe> = <Ausgabe>` stehen etwas anderes?
Soll `ALT + P` dann der Hotkey dafür sein?

**Comment by cssbue** [comment]
Ich würde sagen I: für InputO: für OutputDann sind gleich die Tastenkürzel inmerhalb der Anwendung klar. Okay? ich habe am Mittwoch einen unterrichtsbesuch und werdet da den taschenrechner benutzen in der Lerngruppe. SolveVon meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Lennard Behrens <notifications@github.com>Datum: So., 6. Dez. 2020, 20:01An: behrenle/Math-Explorer <Math-Explorer@noreply.github.com>Cc: cssbue <k.buettner@blista.de>, Author <author@noreply.github.com>Betreff: Re: [behrenle/Math-Explorer] Übergabe von Eingabe und Ausgabe in Zwischenablage (#38)

Wie soll das Format dann aussehen? Soll ich Clipboard dann <Eingabe> = <Ausgabe> stehen etwas anderes?

Soll ALT + P dann der Hotkey dafür sein?



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.


______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by cssbue** [comment]
Mit ALT-P landet jetzt folgendes in der Zwischenablage:
Eingabe: 
Ausgabe:

**Comment by behrenle** [comment]
schon bemerkt und gefixt
