### ISSUE TITLE
Tastenkombinationen CTRL-ALT-I und -O

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#42]
Die Ein- bzw. Ausgabe wird hierdurch geleert, zumindest die Eingabe könnte hierdurch auch fokussiert werden, da man dann in der Regel ja etwas Neues eingeben will.

**Comment by behrenle** [comment]
Das Eingabefeld nach dem Leeren zu fokussieren klingt sinnvoll.

**Comment by behrenle** [comment]
Duplicate of #46
