### ISSUE TITLE
Hilfetext durch klicken kopieren

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#43]
... funktioniert wunderbar, ist aber nicht barrierefrei, weil es keine äquivalente Möglichkeit gibt, dies durch eine Tastatureingabe zu realisieren. Hier müssen wir abwarten, ob die Hilfe überhaupt barrierefrei bedienbar ist - was sagst du dazu, Uli?

**Comment by behrenle** [comment]
Müsste jetzt mit einem Screenreader bedienbar sein, da die Synopsis jetzt einre `role="button"` hat. Zumindest erkennt Chromevox das als Button. Sobald der Button getriggert wird, wird die akutelle Eingabe durch die Synopsis ersetzt und der MathExplorer wechselt zurück in den Calculator View. Zusätzlich handelt es sich beim Manual jetzt um eine `<dl>`, semantisch sinnvoller ist. Ich habe jedoch keine Ahnung ob die Screenreader da einen Unterschied machen...
