### ISSUE TITLE
document mode - Funktionen in type MATH übernehmen

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#59]
Übernahme einer Funktion durch Doppelklick funktioniert nicht. 
Das ist vielleicht auch gut so, denn wohin mit der gewählten Funktion?
In eine neue MATH-Zelle am Ende des Dokuments?

**Comment by behrenle** [comment]
Mir fällt spontan auch keine Variante ein, wie das ergonomisch möglich wäre... Würde es also erstmal weg lassen.
