### ISSUE TITLE
cbinom dbinom

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#60]
Im Unterricht verwendet, weil üblich:
F(n;p;k) statt cbinom(k;n;p)
B(n;p;k) statt dbinom(k;n;p)

Sollten wir lieber beide Schreibweisen zulassen und nur die erste in der Hilfe verwenden?

**Comment by behrenle** [comment]
bin gegen F und B weil das namespace Konflikte gibt. Z. B.: F(x) ist die Stammfunktion von f(x)
