### ISSUE TITLE
Bearbeitung von Zellen im Document-Mode

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#61]
Orientieren wir uns an der Bedienung von Excel?

- [x]  ENTER - Zellinhalt wird editiert (falls Zelle momentan noch nicht bearbeitet wird)
- [x]  ESC - Zelle wird verlassen, Änderungen werden verworfen.
- [x]  ENTER - Änderungen werden gespeichert (falls Zelle momentan editiert wird)
- [x]  ALT+ENTER - Neue Zeile innerhalb der Zelle
- [x]  PFEIL-HOCH PFEIL-RUNTER - Mit Cursortasten bewegen, Schrittweite 1
- [x]  CTRL+PFEIL-HOCH CTRL+PFEIL-RUNTER - Mit Cursortasten bewegen, erste Zelle bzw. letzte Zelle
- [x]  CTRL+S - Dokument speichern
- [x]  CTRL+O - Dokument öffnen

**Comment by behrenle** [comment]
#54
