### ISSUE TITLE
Dokument speichern

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#62]
Die Dateiendung .json hat keinen Wiedererkennungseffekt ... 
Wie wäre es mit einer eigenen Dateiendung?

**Comment by behrenle** [comment]
Glaube der Wiedererkennungswert ist hier nebensächlich. Es gibt schon viel zu viele Dateiendungen und wenn da JSON drin ist sollte auch JSON dran stehen 😅
