### ISSUE TITLE
Document-mode Zeilenumbruch

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#68]
Zeilenumbrüche werden mit ALT-ENTER eingegeben und korrekt dargestellt.
Wenn man den Editiermodus allerdings verlässt, wird alles hintereinander geschrieben.

**Comment by behrenle** [comment]
Der Markdown-Standard verlangt zwei Zeilenumbrüche um einen neuen Absatz zu erzeugen. Ist also ein Markdown Feature und kein Bug. So können komplizierte Ausdrücke in mehrere Zeilen aufgeteilt werden, um später in einer Zeile angezeigt zu werden
