### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#83]
Vielleicht wäre noch ein Shortcut ALT+R "echner" gut, um diesen Tab und die Eingabe zu fokusieren?!?

**Comment by behrenle** [comment]
Finde ich nicht notwendig. Will den ME auch nicht mit hotkeys überladen, weil ich jedes mal prüfen muss, dass der Hotkey nicht von irgendeinem Browser selbst benutzt wird.
