### ISSUE TITLE
Rechnen mit vordefinierten Konstanten 

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#91]
Es ist nicht möglich, die Eulersche Zahl e und die Ludolphsche Zahl pi im Ergebnis als solche anzuzeigen.
Das Multiplikationszeichen zwischen Koeffizient und pi bzw. e muss nicht gesetzt werden. Nach "e" oder "pi" muss aber schon. 
 [bue: Dafür müsste weniger numerisch und mehr algebraisch gerechnet werden. Ich fürchte, dass ist momentan nicht möglich.]

**Comment by behrenle** [comment]
Genau, wird nicht unterstützt.
