### ISSUE TITLE
Terme und Funktionen

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#95]
-) Terme können nicht gespeichert werden!
Eingabe: b:=2x
Ausgabe: RuntimeError: [object Object]
---
-) Speichern von Funktionen
Eingabe: f(x):=2x^2+5
Ausgabe: f(x) := 2 * x^2 + 5

Lennard, brauchen wir Terme? Grübel ...

**Comment by behrenle** [comment]
Nein, brauchen wir nicht.
