### ISSUE TITLE
Operator * implizit

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#96]
-) Versuch, eine Konstante und eine Variable ohne "*" hintereinander zu schreiben, führt zu Fehlern. Statt mit der Eulerschen Zahl oder der Kreiszahl zu rechnen wird jetzt "ex" und "piy" jeweils als eine einzige Variable betrachtet.  [bue: okay. sollte man daher e pi usw. deutlicher von definierten variablen und konstanten unterscheiden? Im Termi war das ja e# oder pi# usw. Vielleicht muss man solche Sonderfälle aber auch einfach nicht abfangen.]

Lennard, auf * kann man ja überwiegend verzichten, aber nicht immer.

**Comment by behrenle** [comment]
Ein Leerzeichen tuts auch, also: `2 pi e`
