### ISSUE TITLE
Intervallgrenzen

### ISSUE THREAD

**Issue by cssbue** [behrenle/Math-Explorer#97]
-) Achtung: eine Lösung wäre genau die obere Grenze und wird nicht ausgegeben!
Eingabe: nsolve(x^2=400)
Ausgabe: [-20] 
[bue: sollte man die Intervallgrenzen also intern etwas erhöhen?]
---

**Comment by behrenle** [comment]
Wie wäre es wenn man in der Dokumentation klar stellt, dass nsolve ein offenes Intervall als Parameter akzeptiert und kein geschlossenes. 
Die Grenzen zu modifizieren ist glaube ich etwas schmutzig.

**Comment by cssbue** [comment]
Im Prinzip kann man das machen, aber ist es ein offenes Intervall?
Mal gehört die Grenze dazu, mal nicht ... doch man kann schon sagen, dass es offen ist. Gut
